Spring:
  application:
    name: smrs-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smrs_user
    password: smrs_pass
    url: jdbc:mysql://14.225.217.153:3306/smrs?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# =======================
# Cloudy Config
# =======================
cloudinary:
  cloud_name: dvn5wyrhv
  api_key: 945984166731914
  api_secret: qOr2LrbP6eBQtFtZk2QlKnOvfY4

---

# =======================
# Mail Config
# =======================
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: baobao280799@gmail.com
    password: ezem hehp pywg dzum
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  base-url: https://smrs.space


copyleaks:
  email: baovhde150401@fpt.edu.vn
  key: d7043682-78f9-4e1a-a262-fec1e38612b5
  login-url: https://id.copyleaks.com/v3/account/login/api
  base-url: https://api.copyleaks.com/v3